"""Crear tabla tipos_convenio

Revision ID: 264cf8e624df
Revises: a6955b63e327
Create Date: 2026-07-28 21:01:19.660604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264cf8e624df'
down_revision = 'a6955b63e327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_convenio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipos_convenio')
    # ### end Alembic commands ###
