"""Crear tabla convenios

Revision ID: 437467b34f00
Revises: 9f1217a2f838
Create Date: 2026-07-27 22:56:41.519759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437467b34f00'
down_revision = '9f1217a2f838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_firma', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convenios')
    # ### end Alembic commands ###
