"""Agregar relaciones a convenios

Revision ID: 718a24118dc2
Revises: 264cf8e624df
Create Date: 2026-07-28 21:15:07.582966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718a24118dc2'
down_revision = '264cf8e624df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tipo_convenio_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'paises', ['pais_id'], ['id'])
        batch_op.create_foreign_key(None, 'tipos_convenio', ['tipo_convenio_id'], ['id'])
        batch_op.create_foreign_key(None, 'actores', ['actor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('convenios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tipo_convenio_id')
        batch_op.drop_column('actor_id')
        batch_op.drop_column('pais_id')

    # ### end Alembic commands ###
