"""Crear tabla paises

Revision ID: 922f276a9b29
Revises: 437467b34f00
Create Date: 2026-07-28 19:55:12.354844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922f276a9b29'
down_revision = '437467b34f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.String(length=3), nullable=False),
    sa.Column('continente', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paises')
    # ### end Alembic commands ###
